"""add_portfolio_signal_feedback_tables

Revision ID: 9863acc83e39
Revises: cb268f53e627
Create Date: 2026-05-29 17:50:01.941501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9863acc83e39'
down_revision: Union[str, Sequence[str], None] = 'cb268f53e627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_symbol', sa.String(length=20), nullable=False),
    sa.Column('review_start', sa.DateTime(), nullable=False),
    sa.Column('review_end', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('total_signals', sa.Integer(), nullable=False),
    sa.Column('correct_signals', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=100), nullable=False),
    sa.Column('problem_diagnosis', sa.Text(), nullable=False),
    sa.Column('suggested_adjustments', sa.Text(), nullable=False),
    sa.Column('learning_points', sa.Text(), nullable=False),
    sa.Column('llm_raw_response', sa.JSON(), nullable=True),
    sa.Column('is_pushed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_reviews_id'), 'signal_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_signal_reviews_reviewed_at'), 'signal_reviews', ['reviewed_at'], unique=False)
    op.create_index(op.f('ix_signal_reviews_target_symbol'), 'signal_reviews', ['target_symbol'], unique=False)
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fund_code', sa.String(length=20), nullable=False),
    sa.Column('fund_name', sa.String(length=100), nullable=False),
    sa.Column('fund_type', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('cost_total', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_pct', sa.Float(), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_portfolio_user_fund', 'portfolio', ['user_id', 'fund_code'], unique=True)
    op.create_index(op.f('ix_portfolio_id'), 'portfolio', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_table('portfolio_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fund_code', sa.String(length=20), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('profit_loss_pct', sa.Float(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('action_label', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('llm_raw_response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_analyses_analyzed_at'), 'portfolio_analyses', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_portfolio_analyses_fund_code'), 'portfolio_analyses', ['fund_code'], unique=False)
    op.create_index(op.f('ix_portfolio_analyses_id'), 'portfolio_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_analyses_user_id'), 'portfolio_analyses', ['user_id'], unique=False)
    op.create_table('signal_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.DateTime(), nullable=False),
    sa.Column('target_symbol', sa.String(length=20), nullable=False),
    sa.Column('predicted_signal', sa.String(length=20), nullable=False),
    sa.Column('blogger_consensus_score', sa.Float(), nullable=False),
    sa.Column('news_sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('actual_change_pct', sa.Float(), nullable=False),
    sa.Column('actual_direction', sa.String(length=10), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('error_magnitude', sa.Float(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['daily_signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sigverify_symbol_date', 'signal_verifications', ['target_symbol', 'signal_date'], unique=True)
    op.create_index(op.f('ix_signal_verifications_id'), 'signal_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_signal_verifications_signal_date'), 'signal_verifications', ['signal_date'], unique=False)
    op.create_index(op.f('ix_signal_verifications_signal_id'), 'signal_verifications', ['signal_id'], unique=False)
    op.create_index(op.f('ix_signal_verifications_target_symbol'), 'signal_verifications', ['target_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_verifications_target_symbol'), table_name='signal_verifications')
    op.drop_index(op.f('ix_signal_verifications_signal_id'), table_name='signal_verifications')
    op.drop_index(op.f('ix_signal_verifications_signal_date'), table_name='signal_verifications')
    op.drop_index(op.f('ix_signal_verifications_id'), table_name='signal_verifications')
    op.drop_index('idx_sigverify_symbol_date', table_name='signal_verifications')
    op.drop_table('signal_verifications')
    op.drop_index(op.f('ix_portfolio_analyses_user_id'), table_name='portfolio_analyses')
    op.drop_index(op.f('ix_portfolio_analyses_id'), table_name='portfolio_analyses')
    op.drop_index(op.f('ix_portfolio_analyses_fund_code'), table_name='portfolio_analyses')
    op.drop_index(op.f('ix_portfolio_analyses_analyzed_at'), table_name='portfolio_analyses')
    op.drop_table('portfolio_analyses')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_id'), table_name='portfolio')
    op.drop_index('idx_portfolio_user_fund', table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_signal_reviews_target_symbol'), table_name='signal_reviews')
    op.drop_index(op.f('ix_signal_reviews_reviewed_at'), table_name='signal_reviews')
    op.drop_index(op.f('ix_signal_reviews_id'), table_name='signal_reviews')
    op.drop_table('signal_reviews')
    # ### end Alembic commands ###
