"""add_retail_sentiment_and_signal_field

Revision ID: bce95bc028dc
Revises: a4f7c2e81b93
Create Date: 2026-06-16 12:57:33.189610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce95bc028dc'
down_revision: Union[str, Sequence[str], None] = 'a4f7c2e81b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retail_sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('bullish_ratio', sa.Float(), nullable=True),
    sa.Column('bearish_ratio', sa.Float(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retail_sentiments_captured_at'), 'retail_sentiments', ['captured_at'], unique=False)
    op.create_index(op.f('ix_retail_sentiments_id'), 'retail_sentiments', ['id'], unique=False)
    op.create_index(op.f('ix_retail_sentiments_source'), 'retail_sentiments', ['source'], unique=False)
    op.create_index(op.f('ix_retail_sentiments_symbol'), 'retail_sentiments', ['symbol'], unique=False)
    op.add_column('daily_signals', sa.Column('retail_sentiment_score', sa.Float(), nullable=True, server_default='0.0'))
    op.execute("UPDATE daily_signals SET retail_sentiment_score = 0.0 WHERE retail_sentiment_score IS NULL")
    op.alter_column('daily_signals', 'retail_sentiment_score', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_signals', 'retail_sentiment_score')
    op.drop_index(op.f('ix_retail_sentiments_symbol'), table_name='retail_sentiments')
    op.drop_index(op.f('ix_retail_sentiments_source'), table_name='retail_sentiments')
    op.drop_index(op.f('ix_retail_sentiments_id'), table_name='retail_sentiments')
    op.drop_index(op.f('ix_retail_sentiments_captured_at'), table_name='retail_sentiments')
    op.drop_table('retail_sentiments')
    # ### end Alembic commands ###
