"""initial

Revision ID: cb268f53e627
Revises: 
Create Date: 2026-05-29 15:37:06.193973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb268f53e627'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_user_id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('correct_predictions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blogger_platform_user', 'bloggers', ['platform', 'platform_user_id'], unique=True)
    op.create_index(op.f('ix_bloggers_id'), 'bloggers', ['id'], unique=False)
    op.create_index(op.f('ix_bloggers_platform_user_id'), 'bloggers', ['platform_user_id'], unique=False)
    op.create_table('crawl_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawler_name', sa.String(length=50), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_saved', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_snapshot', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_logs_crawler_name'), 'crawl_logs', ['crawler_name'], unique=False)
    op.create_index(op.f('ix_crawl_logs_id'), 'crawl_logs', ['id'], unique=False)
    op.create_index(op.f('ix_crawl_logs_run_at'), 'crawl_logs', ['run_at'], unique=False)
    op.create_table('daily_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_date', sa.DateTime(), nullable=False),
    sa.Column('target_symbol', sa.String(length=20), nullable=False),
    sa.Column('target_name', sa.String(length=50), nullable=False),
    sa.Column('blogger_consensus_score', sa.Float(), nullable=False),
    sa.Column('news_sentiment_score', sa.Float(), nullable=False),
    sa.Column('final_signal', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('participating_bloggers', sa.Integer(), nullable=False),
    sa.Column('analyzed_news_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_signals_id'), 'daily_signals', ['id'], unique=False)
    op.create_index(op.f('ix_daily_signals_signal_date'), 'daily_signals', ['signal_date'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_symbol_date', 'market_data', ['symbol', 'trade_date'], unique=True)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_trade_date'), 'market_data', ['trade_date'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('publish_time', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('llm_analysis', sa.Text(), nullable=True),
    sa.Column('llm_raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=False)
    op.create_index(op.f('ix_news_publish_time'), 'news', ['publish_time'], unique=False)
    op.create_index(op.f('ix_news_url'), 'news', ['url'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('telegram_bind_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('third_party_order_no', sa.String(length=100), nullable=True),
    sa.Column('raw_callback_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_no'), 'orders', ['order_no'], unique=True)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blogger_id', sa.Integer(), nullable=False),
    sa.Column('post_url', sa.String(length=500), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=False),
    sa.Column('predicted_direction', sa.String(length=10), nullable=True),
    sa.Column('predicted_target', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('llm_reasoning', sa.Text(), nullable=True),
    sa.Column('llm_raw_response', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_prediction', sa.Boolean(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blogger_id'], ['bloggers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_blogger_id'), 'predictions', ['blogger_id'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_post_time'), 'predictions', ['post_time'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_user_symbol', 'watchlist', ['user_id', 'symbol'], unique=True)
    op.create_index(op.f('ix_watchlist_id'), 'watchlist', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_user_id'), 'watchlist', ['user_id'], unique=False)
    op.create_table('prediction_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('verification_date', sa.DateTime(), nullable=False),
    sa.Column('actual_change_pct', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_verifications_id'), 'prediction_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_verifications_prediction_id'), 'prediction_verifications', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_prediction_verifications_verification_date'), 'prediction_verifications', ['verification_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_verifications_verification_date'), table_name='prediction_verifications')
    op.drop_index(op.f('ix_prediction_verifications_prediction_id'), table_name='prediction_verifications')
    op.drop_index(op.f('ix_prediction_verifications_id'), table_name='prediction_verifications')
    op.drop_table('prediction_verifications')
    op.drop_index(op.f('ix_watchlist_user_id'), table_name='watchlist')
    op.drop_index(op.f('ix_watchlist_id'), table_name='watchlist')
    op.drop_index('idx_watchlist_user_symbol', table_name='watchlist')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_predictions_post_time'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_blogger_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_no'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_news_url'), table_name='news')
    op.drop_index(op.f('ix_news_publish_time'), table_name='news')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_market_data_trade_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index('idx_market_symbol_date', table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_daily_signals_signal_date'), table_name='daily_signals')
    op.drop_index(op.f('ix_daily_signals_id'), table_name='daily_signals')
    op.drop_table('daily_signals')
    op.drop_index(op.f('ix_crawl_logs_run_at'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_id'), table_name='crawl_logs')
    op.drop_index(op.f('ix_crawl_logs_crawler_name'), table_name='crawl_logs')
    op.drop_table('crawl_logs')
    op.drop_index(op.f('ix_bloggers_platform_user_id'), table_name='bloggers')
    op.drop_index(op.f('ix_bloggers_id'), table_name='bloggers')
    op.drop_index('idx_blogger_platform_user', table_name='bloggers')
    op.drop_table('bloggers')
    # ### end Alembic commands ###
